apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-clusterip-service
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoami
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  # THE Below will make a 'global default service'
  # backend:
  #  serviceName: whoami
  #  servicePort: 80
  rules:
  # whoami.minikube must be in your hosts file (pointing to `minikube ip`)
  - host: whoami.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami-clusterip-service
          servicePort: 80
  # whoami.com must be in your hosts file (pointing to `minikube ip`)
  - host: whoami.com
    http:
      paths:
      - path: /
        backend:
          serviceName: whoami-clusterip-service
          servicePort: 80
  # tls:
  # - hosts:
  #   - whoami.com
  #   - whoami.minikube
